config/routes.rb
QuestionAndAnswer::Application.routes.draw do
  devise_for :users

  root :to => "questions#index"

  resources :questions

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :answer, :last_edited_by, :title
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_and_belongs_to_many :questions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  def index
    @questions = Question.all

  end

  def show
    @question = Question.find(params[:id])
    @last_edited_by = User.find(@question.last_edited_by)
  end

  def new
    @question = Question.new

  end

  def edit
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.new(params[:question])
    @question.users << current_user
    @question.last_edited_by = current_user.id
    if @question.save
      flash[:notice] = "Question has been created."
      redirect_to @question
    else
      # nothing
    end
  end

  def update
    @question = Question.find(params[:id])
    unless @question.users.include? current_user
      @question.users << current_user
    end
    @question.last_edited_by = current_user.id
    if @question.update_attributes(params[:question])
      flash[:notice] = "Question has been updated."
      redirect_to @question
    else
      flash[:alert] = "Question has not been updated."
      render :action => "edit"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuestionAndAnswer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <div class="flash" id="<%= key %>">
    <%= value %>
  </div>
<% end %>

<nav>
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %>
    <%= link_to "Sign in", new_user_session_path %>
  <% end %>
</nav>

<hr>

<%= yield %>

</body>
</html>

app/views/questions/edit.html.erb
<h2><%= @question.title %></h2>
<%= form_for(@question) do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :answer %><br />
    <%= f.text_field :answer %>
  </p>
  <%= f.submit %>
<% end %>

app/views/questions/index.html.erb
<h2>Questions</h2>
<img src="assets/answeryourownquestion.gif" alt="Fry Meme, don't answer your own question" style="height: 200px;" >
<ul>
<% @questions.each do |question| %>
<li><%= link_to question.title, question %> </li>
<% end %>
</ul>

<%= link_to "New Question", new_question_path %>

app/views/questions/new.html.erb
<h2>New Question</h2>
<%= form_for(@question) do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :answer %><br />
    <%= f.text_field :answer %>
  </p>
  <%= f.submit %>
<% end %>

app/views/questions/show.html.erb
<h2><%= @question.title %></h2>
<p>Answer: <%= @question.answer %></p>
<p>Last Edited By: <%= @last_edited_by.email %></p>
<h3>Contributors:</h3>
<ul>
  <% @question.users.each do |user| %>
    <li><%= user.email %></li>
  <% end %>
</ul>

<p><%= link_to "Edit Question", edit_question_path %></p>
<%= link_to "New Question", new_question_path %>
<%= link_to "All Questions", questions_path %>